In [5]:
import numpy as np
a=np.array([0,1,2,0,3,4,0,5,6,0,0,0,0,0,0]).reshape(5,3)

a
# array([[0, 1, 2],
#        [0, 3, 4],
#        [0, 5, 6],
#        [0, 0, 0],
#        [0, 0, 0]])



array([[0, 1, 2],
       [0, 3, 4],
       [0, 5, 6],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
#去除全零行
a = a[a.sum(axis=1)!=0,:]
a
# array([[0, 1, 2],
#        [0, 3, 4],
#        [0, 5, 6]])

array([[0, 1, 2],
       [0, 3, 4],
       [0, 5, 6]])

In [9]:
#去除全零列
a = a[:,a.sum(axis=0)!=0]
a
# array([[1, 2],
#        [3, 4],
#        [5, 6],
#        [0, 0],
#        [0, 0]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
import numpy as np

arrayA = np.arange(8)
# arrayA = array([0, 1, 2, 3, 4, 5, 6, 7])

a1 = np.reshape(arrayA, (2, 4))
a1 

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [11]:
a2 = np.reshape(a1, (4, 4))
a2

ValueError: cannot reshape array of size 8 into shape (4,4)

In [12]:
import csv
import numpy as np

a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# 将3D数组转换为2D数组
a2d = a.reshape(a.shape[0], -1)

# 将2D数组写入csv文件
with open("output.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(a2d)

In [14]:
import csv
import numpy as np

# 从csv文件读取2D数组
with open("output.csv", "r") as f:
    reader = csv.reader(f)
    a2d = np.array(list(reader)).astype("int")

# 将2D数组转换为3D数组
a = a2d.reshape((-1, 2, 3))
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
